export const donations = [
    {
      id: 1,
      hospital: "بنك دم المركز القومي",
      date: "15 أكتوبر 2023",
      amount: "450 مل (كيس واحد)",
      status: "مكتمل",
      active: true,
    },
    {
      id: 2,
      hospital: "مستشفى القصر العيني",
      date: "12 يونيو 2023",
      amount: "450 مل (كيس واحد)",
      status: "مكتمل",
      active: true,
    },
    {
      id: 3,
      hospital: "بنك دم الدقي",
      date: "05 فبراير 2023",
      amount: "450 مل (كيس واحد)",
      status: "مكتمل",
      active: true,
    },
    {
      id: 4,
      hospital: "بنك دم الهلال الأحمر",
      date: "20 سبتمبر 2022",
      amount: "",
      status: "2022",
      active: false,
    },
    {
      id: 5,
      hospital: "مستشفى القصر العيني",
      date: "12 يونيو 2023",
      amount: "450 مل (كيس واحد)",
      status: "مكتمل",
      active: true,
    },
    {
      id: 6,
      hospital: "بنك دم الدقي",
      date: "05 فبراير 2023",
      amount: "450 مل (كيس واحد)",
      status: "مكتمل",
      active: true,
    },
    {
      id: 7,
      hospital: "بنك دم الهلال الأحمر",
      date: "20 سبتمبر 2022",
      amount: "",
      status: "2022",
      active: false,
    },
  ];